### PR TITLE
DI-1271 v2.0.1 Add 'Sample' back in to output file

### PR DESCRIPTION
**Pull request by rklocke**
- Add Sample back in as first column of output TSV
- Update version and whatsNew in dxapp.json
- Fix unit tests
- Nicer README

Example job with TWE38 sample with v2.0.1:
https://platform.dnanexus.com/panx/projects/Gx3Pj984g32qxb9xfQJ3j316/monitor/job/Gx3Q2904g32xqxBPfY6p3B4J

Job for same sample with v2.0.0 for comparison:
https://platform.dnanexus.com/panx/projects/GqFY1F04JK8pQ0kFfx9P2Ykv/monitor/job/Gv4Y0g04JK8v0QyK4zFG1vZ3

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf_qc/16)

### CODE REVIEW

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf_qc/16)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @rklocke)

___
*[`src/vcf_qc.py` line 51 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcf_qc/16#-OChPUF9A6ZOyJUzYh53:-OChPUF9A6ZOyJUzYh54:b4os1vi) ([raw file](https://github.com/eastgenomics/eggd_vcf_qc/blob/9daca3a1b46fb6dc92c5b61f4c32e6bcdc92bdae/src/vcf_qc.py#L51)):*
if you are catching a specific exception type, why then raise an `AssertionError`? If you want to just add a custom error to the exception, you could do:

```
>>> try:
...     re.compile(r'[')
... except re.error as err:
...     raise RuntimeError('you did a dumb') from err
... 
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/usr/lib/python3.8/re.py", line 252, in compile
    return _compile(pattern, flags)
  File "/usr/lib/python3.8/re.py", line 304, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib/python3.8/sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/lib/python3.8/sre_parse.py", line 948, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
  File "/usr/lib/python3.8/sre_parse.py", line 443, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
  File "/usr/lib/python3.8/sre_parse.py", line 549, in _parse
    raise source.error("unterminated character set",
re.error: unterminated character set at position 0

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
RuntimeError: you did a dumb

```



_Code quote:_
```Python
    except subprocess.CalledProcessError as e:
        raise AssertionError(
            f"Error in calling bedtools intersect: {e.stderr.decode()}"
        )
```

**Review by rklocke — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf_qc/16)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @jethror1)

___
*[`src/vcf_qc.py` line 51 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcf_qc/16#-OChPUF9A6ZOyJUzYh53:-OChTb4WExwqEkAdEFzc:b4sxwf1) ([raw file](https://github.com/eastgenomics/eggd_vcf_qc/blob/9daca3a1b46fb6dc92c5b61f4c32e6bcdc92bdae/src/vcf_qc.py#L51)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

if you are catching a specific exception type, why then raise an `AssertionError`? If you want to just add a custom error to the exception, you could do:

```
>>> try:
...     re.compile(r'[')
... except re.error as err:
...     raise RuntimeError('you did a dumb') from err
... 
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/usr/lib/python3.8/re.py", line 252, in compile
    return _compile(pattern, flags)
  File "/usr/lib/python3.8/re.py", line 304, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib/python3.8/sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/lib/python3.8/sre_parse.py", line 948, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
  File "/usr/lib/python3.8/sre_parse.py", line 443, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
  File "/usr/lib/python3.8/sre_parse.py", line 549, in _parse
    raise source.error("unterminated character set",
re.error: unterminated character set at position 0

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
RuntimeError: you did a dumb

```
</blockquote></details>

like this?

**Review by jethror1 — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf_qc/16)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @rklocke)

**Review by jethror1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf_qc/16)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @rklocke)

**Pull request merged**
