### PR TITLE
Initialise

### PR DESCRIPTION
**Pull request by mattgarner**
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf_qc/2)

### CODE REVIEW

**Review by Yu-jinKim — COMMENTED** [review]
> Reviewed 5 of 6 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf_qc/2)* status: all files reviewed, 8 unresolved discussions (waiting on @mattgarner)

___
*[resources/usr/bin/vcf_QC.py, line 26 at r2](https://reviewable.io/reviews/eastgenomics/eggd_vcf_qc/2#-M4TN7wR2QB97LiCIvjT:-M4TN7wR2QB97LiCIvjU:b-fs6s8x) ([raw file](https://github.com/eastgenomics/eggd_vcf_qc/blob/8bd4483c300e513e26341eabd39b90c71c0e3617/resources/usr/bin/vcf_QC.py#L26)):*
> ```Python
> 
>     # Make temp on-target vcf
>     #target_bed = "/mnt/storage/refs/human_1kg/TruSightOne_plus/TSOnePlus.bed"
> ```

Probably should get rid of this line
___
*[resources/usr/bin/vcf_QC.py, line 27 at r2](https://reviewable.io/reviews/eastgenomics/eggd_vcf_qc/2#-M4TOhRA2jKsMfX_8V9x:-M4TOhRA2jKsMfX_8V9y:b-36me2m) ([raw file](https://github.com/eastgenomics/eggd_vcf_qc/blob/8bd4483c300e513e26341eabd39b90c71c0e3617/resources/usr/bin/vcf_QC.py#L27)):*
> ```
>     vcf_basename = os.path.basename(vcf_file)
>     vcf_runfolder = vcf_file.split("/vcfs")[0].split("/")[-1]
> ```
Using kim's old runfolder structure, so not usable in DNAnexus
___
*[resources/usr/bin/vcf_QC.py, line 133 at r2](https://reviewable.io/reviews/eastgenomics/eggd_vcf_qc/2#-M4TOpWYD-WnO4PlIZZy:-M4TOpWYD-WnO4PlIZZz:bm2s2kn) ([raw file](https://github.com/eastgenomics/eggd_vcf_qc/blob/8bd4483c300e513e26341eabd39b90c71c0e3617/resources/usr/bin/vcf_QC.py#L133)):*
> ```Python
>         X_het_hom_ratio = "{:.4f}".format( X_het_hom_ratio )
> 
>         print( "\t".join( [ vcf_runfolder, sample, mean_het, mean_hom, het_hom_ratio, str(het_score), str(hom_score), het_hom_score, X_het_hom_ratio, gender]))
> ```

Match with the removal of vcf_runfolder
___
*[resources/usr/bin/vcf_QC.py, line 135 at r2](https://reviewable.io/reviews/eastgenomics/eggd_vcf_qc/2#-M4TOKHV5AeJbpm4JDpK:-M4TOKHV5AeJbpm4JDpL:b-x1wj0h) ([raw file](https://github.com/eastgenomics/eggd_vcf_qc/blob/8bd4483c300e513e26341eabd39b90c71c0e3617/resources/usr/bin/vcf_QC.py#L135)):*
> ```Python
>         print( "\t".join( [ vcf_runfolder, sample, mean_het, mean_hom, het_hom_ratio, str(het_score), str(hom_score), het_hom_score, X_het_hom_ratio, gender]))
> 
>     os.remove(temp_vcf)
> ```

Not necessary and might be useful to keep the tmp vcf for debugging?
___
*[resources/usr/bin/vcf_QC.py, line 142 at r2](https://reviewable.io/reviews/eastgenomics/eggd_vcf_qc/2#-M4TNfZsC6Lk5i-9Fkz6:-M4TNfZsC6Lk5i-9Fkz7:b-amdpdi) ([raw file](https://github.com/eastgenomics/eggd_vcf_qc/blob/8bd4483c300e513e26341eabd39b90c71c0e3617/resources/usr/bin/vcf_QC.py#L142)):*
> ```Python
>     parser = argparse.ArgumentParser(description='vcf_QC.py: simple QC of a vcf file ')
> 
>     parser.add_argument('-o', '--outfile', help="if set writes to this file")
> ```

Do we want to keep that ?
___
*[resources/usr/bin/vcf_QC.py, line 149 at r2](https://reviewable.io/reviews/eastgenomics/eggd_vcf_qc/2#-M4TOBGW3RSEVUQ__xE3:-M4TOBGW3RSEVUQ__xE4:bf588su) ([raw file](https://github.com/eastgenomics/eggd_vcf_qc/blob/8bd4483c300e513e26341eabd39b90c71c0e3617/resources/usr/bin/vcf_QC.py#L149)):*
> ```
>     if args.outfile:
>         sys.stdout = open("{}".format( args.outfile), 'w')
> ```

Not use anymore
___
*[resources/usr/bin/vcf_QC.py, line 151 at r2](https://reviewable.io/reviews/eastgenomics/eggd_vcf_qc/2#-M4TOuj5-xwLXuNT-Sv2:-M4TOuj5-xwLXuNT-Sv3:bguc031) ([raw file](https://github.com/eastgenomics/eggd_vcf_qc/blob/8bd4483c300e513e26341eabd39b90c71c0e3617/resources/usr/bin/vcf_QC.py#L151)):*
> ```Python
>         sys.stdout = open("{}".format( args.outfile), 'w')
> 
>     print "\t".join([ "Runfolder", "Sample", "mean het ratio", "mean homo ratio", "het:homo ratio", "het-score", "hom-score", "het-homo score", "X homo:het ratio", "gender"])
> ```

Match with the removal of runfolder
___
*[src/dnanexus_vcf_QC.sh, line 32 at r2](https://reviewable.io/reviews/eastgenomics/eggd_vcf_qc/2#-M4TP5JY1QJ5CyR14wTX:-M4TP5JY1QJ5CyR14wTY:br23n6q) ([raw file](https://github.com/eastgenomics/eggd_vcf_qc/blob/8bd4483c300e513e26341eabd39b90c71c0e3617/src/dnanexus_vcf_QC.sh#L32)):*
> ```Shell
>     dx download "$bed_file" -o bed_file
> 
>     output_file_name="${vcf_file_prefix}.vcf.QC"
> ```

does it have a default?

**Review by woook — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf_qc/2)* status: all files reviewed, 12 unresolved discussions (waiting on @mattgarner)

___
*[dxapp.json, line 49 at r2](https://reviewable.io/reviews/eastgenomics/eggd_vcf_qc/2#-M4UG8Oz4u_ayoDkKywB:-M4UG8P-DIcrocFU42aO:b-9m8sdd) ([raw file](https://github.com/eastgenomics/eggd_vcf_qc/blob/8bd4483c300e513e26341eabd39b90c71c0e3617/dxapp.json#L49)):*
> ```
>       {"name": "bedtools",
> ```

Do you need to specify a version?
___
*[README.md, line 8 at r2](https://reviewable.io/reviews/eastgenomics/eggd_vcf_qc/2#-M4UGWeg4UhNhqW8ju86:-M4UGWeg4UhNhqW8ju87:b-kep02u) ([raw file](https://github.com/eastgenomics/eggd_vcf_qc/blob/8bd4483c300e513e26341eabd39b90c71c0e3617/README.md#L8)):*
> ```
> This is the source code for an app that runs on the DNAnexus Platform.
> For more information about how to run or modify it, see
> https://documentation.dnanexus.com/.
> ```
Not sure this statement should be here seeing as the readme is displayed in the app on the website.
___
*[README.md, line 27 at r2](https://reviewable.io/reviews/eastgenomics/eggd_vcf_qc/2#-M4UJD_17jNgEq590LI6:-M4UJD_17jNgEq590LI7:be3g6qv) ([raw file](https://github.com/eastgenomics/eggd_vcf_qc/blob/8bd4483c300e513e26341eabd39b90c71c0e3617/README.md#L27)):*
> ```
>  - hom-score (mean deviation from 1.0 in hom variants)
> ```
is this equivalent to 1 - [mean homo ratio]?
___
*[Readme.md, line 1 at r2](https://reviewable.io/reviews/eastgenomics/eggd_vcf_qc/2#-M4UKe0-3rJ0UpBsDZ9N:-M4UKe0-3rJ0UpBsDZ9O:b-n7g5pe) ([raw file](https://github.com/eastgenomics/eggd_vcf_qc/blob/8bd4483c300e513e26341eabd39b90c71c0e3617/Readme.md#L1)):*
> ```
> 
> ```
Why does this files exist?

**Review by mattgarner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf_qc/2)* status: 2 of 5 files reviewed, 12 unresolved discussions (waiting on @woook and @Yu-jinKim)

___
*[dxapp.json, line 49 at r2](https://reviewable.io/reviews/eastgenomics/eggd_vcf_qc/2#-M4UG8Oz4u_ayoDkKywB:-M4oXe7zA41gMbJB_MQy:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_vcf_qc/blob/8bd4483c300e513e26341eabd39b90c71c0e3617/dxapp.json#L49)):*
<details><summary><i>Previously, woook wrote…</i></summary><blockquote>

> ```
>       {"name": "bedtools",
> ```

Do you need to specify a version?
</blockquote></details>

Done.
___
*[README.md, line 8 at r2](https://reviewable.io/reviews/eastgenomics/eggd_vcf_qc/2#-M4UGWeg4UhNhqW8ju86:-M4oXxOY7UY4g_-xfori:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_vcf_qc/blob/8bd4483c300e513e26341eabd39b90c71c0e3617/README.md#L8)):*
<details><summary><i>Previously, woook wrote…</i></summary><blockquote>

> ```
> This is the source code for an app that runs on the DNAnexus Platform.
> For more information about how to run or modify it, see
> https://documentation.dnanexus.com/.
> ```
Not sure this statement should be here seeing as the readme is displayed in the app on the website.
</blockquote></details>

Done.
___
*[README.md, line 27 at r2](https://reviewable.io/reviews/eastgenomics/eggd_vcf_qc/2#-M4UJD_17jNgEq590LI6:-M4oYnmn8VCZCxKEiq2n:b-83zbq2) ([raw file](https://github.com/eastgenomics/eggd_vcf_qc/blob/8bd4483c300e513e26341eabd39b90c71c0e3617/README.md#L27)):*
<details><summary><i>Previously, woook wrote…</i></summary><blockquote>

> ```
>  - hom-score (mean deviation from 1.0 in hom variants)
> ```
is this equivalent to 1 - [mean homo ratio]?
</blockquote></details>

Almost, it's that x 100 (i.e. % deviation from 1). 
I understand your point though, there's not really any reason to return both numbers, and having a mix of fractions and percentages is confusing. I'll keep the mean homo/het ratios and het:hom ratio, and drop the het/hom/het-hom scores
___
*[Readme.md, line 1 at r2](https://reviewable.io/reviews/eastgenomics/eggd_vcf_qc/2#-M4UKe0-3rJ0UpBsDZ9N:-M4o_HGJ2Pc5zzTqM87a:b-t3gbnm) ([raw file](https://github.com/eastgenomics/eggd_vcf_qc/blob/8bd4483c300e513e26341eabd39b90c71c0e3617/Readme.md#L1)):*
<details><summary><i>Previously, woook wrote…</i></summary><blockquote>

> ```
> 
> ```
Why does this files exist?
</blockquote></details>

Laziness, I populated the wrong readme then transferred the content to the correct one. Removed
___
*[resources/usr/bin/vcf_QC.py, line 26 at r2](https://reviewable.io/reviews/eastgenomics/eggd_vcf_qc/2#-M4TN7wR2QB97LiCIvjT:-M4oWIP_9o6n5oxkgxln:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_vcf_qc/blob/8bd4483c300e513e26341eabd39b90c71c0e3617/resources/usr/bin/vcf_QC.py#L26)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

Probably should get rid of this line
</blockquote></details>

Done.
___
*[resources/usr/bin/vcf_QC.py, line 27 at r2](https://reviewable.io/reviews/eastgenomics/eggd_vcf_qc/2#-M4TOhRA2jKsMfX_8V9x:-M4oWJPY00-WK45nHDto:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_vcf_qc/blob/8bd4483c300e513e26341eabd39b90c71c0e3617/resources/usr/bin/vcf_QC.py#L27)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

> ```
>     vcf_basename = os.path.basename(vcf_file)
>     vcf_runfolder = vcf_file.split("/vcfs")[0].split("/")[-1]
> ```
Using kim's old runfolder structure, so not usable in DNAnexus
</blockquote></details>

Done.
___
*[resources/usr/bin/vcf_QC.py, line 133 at r2](https://reviewable.io/reviews/eastgenomics/eggd_vcf_qc/2#-M4TOpWYD-WnO4PlIZZy:-M4oWKzu4pCLgoYIyvdL:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_vcf_qc/blob/8bd4483c300e513e26341eabd39b90c71c0e3617/resources/usr/bin/vcf_QC.py#L133)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

Match with the removal of vcf_runfolder
</blockquote></details>

Done.
___
*[resources/usr/bin/vcf_QC.py, line 135 at r2](https://reviewable.io/reviews/eastgenomics/eggd_vcf_qc/2#-M4TOKHV5AeJbpm4JDpK:-M4oWLtf5PfcOnkFc45j:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_vcf_qc/blob/8bd4483c300e513e26341eabd39b90c71c0e3617/resources/usr/bin/vcf_QC.py#L135)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

Not necessary and might be useful to keep the tmp vcf for debugging?
</blockquote></details>

Done.
___
*[resources/usr/bin/vcf_QC.py, line 142 at r2](https://reviewable.io/reviews/eastgenomics/eggd_vcf_qc/2#-M4TNfZsC6Lk5i-9Fkz6:-M4oWMrW1OI_gLXzFRpl:b-ads79s) ([raw file](https://github.com/eastgenomics/eggd_vcf_qc/blob/8bd4483c300e513e26341eabd39b90c71c0e3617/resources/usr/bin/vcf_QC.py#L142)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

Do we want to keep that ?
</blockquote></details>

I'm going to keep it as it's useful if running the script locally, but you're right that it is not used when run in DNAnexus
___
*[resources/usr/bin/vcf_QC.py, line 149 at r2](https://reviewable.io/reviews/eastgenomics/eggd_vcf_qc/2#-M4TOBGW3RSEVUQ__xE3:-M4oW_b00X_IHQ6aHUZM:bighjnt) ([raw file](https://github.com/eastgenomics/eggd_vcf_qc/blob/8bd4483c300e513e26341eabd39b90c71c0e3617/resources/usr/bin/vcf_QC.py#L149)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

> ```
>     if args.outfile:
>         sys.stdout = open("{}".format( args.outfile), 'w')
> ```

Not use anymore
</blockquote></details>

See previous
___
*[resources/usr/bin/vcf_QC.py, line 151 at r2](https://reviewable.io/reviews/eastgenomics/eggd_vcf_qc/2#-M4TOuj5-xwLXuNT-Sv2:-M4oWe2b-FTp7mfcJzAy:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_vcf_qc/blob/8bd4483c300e513e26341eabd39b90c71c0e3617/resources/usr/bin/vcf_QC.py#L151)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

Match with the removal of runfolder
</blockquote></details>

Done.
___
*[src/dnanexus_vcf_QC.sh, line 32 at r2](https://reviewable.io/reviews/eastgenomics/eggd_vcf_qc/2#-M4TP5JY1QJ5CyR14wTX:-M4oWkGn52WnSRaN2rHU:b-fqqtdv) ([raw file](https://github.com/eastgenomics/eggd_vcf_qc/blob/8bd4483c300e513e26341eabd39b90c71c0e3617/src/dnanexus_vcf_QC.sh#L32)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

does it have a default?
</blockquote></details>

A default output file name? I think I would prefer that it always contain the sample ID, but I'm certainly open to being persuaded if there's a use case for having a default

**Review by Yu-jinKim — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf_qc/2)* status: 2 of 5 files reviewed, 12 unresolved discussions (waiting on @mattgarner, @woook, and @Yu-jinKim)

___
*[src/dnanexus_vcf_QC.sh, line 32 at r2](https://reviewable.io/reviews/eastgenomics/eggd_vcf_qc/2#-M4TP5JY1QJ5CyR14wTX:-M4rspm75mXX2L47npHS:b-49zwqg) ([raw file](https://github.com/eastgenomics/eggd_vcf_qc/blob/8bd4483c300e513e26341eabd39b90c71c0e3617/src/dnanexus_vcf_QC.sh#L32)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

A default output file name? I think I would prefer that it always contain the sample ID, but I'm certainly open to being persuaded if there's a use case for having a default
</blockquote></details>

I don't see the vcf_file_prefix defined in the bash script and it's not in the dxapp.json that's why i'm asking

**Review by Yu-jinKim — COMMENTED** [review]
> Reviewed 1 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf_qc/2)* status: 3 of 5 files reviewed, 5 unresolved discussions (waiting on @mattgarner, @woook, and @Yu-jinKim)

**Review by mattgarner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf_qc/2)* status: 3 of 5 files reviewed, 5 unresolved discussions (waiting on @woook and @Yu-jinKim)

___
*[src/dnanexus_vcf_QC.sh, line 32 at r2](https://reviewable.io/reviews/eastgenomics/eggd_vcf_qc/2#-M4TP5JY1QJ5CyR14wTX:-M4wiPHH9oyV7V-qGq2B:b-xduin) ([raw file](https://github.com/eastgenomics/eggd_vcf_qc/blob/8bd4483c300e513e26341eabd39b90c71c0e3617/src/dnanexus_vcf_QC.sh#L32)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

I don't see the vcf_file_prefix defined in the bash script and it's not in the dxapp.json that's why i'm asking
</blockquote></details>

Sorry, I misunderstood. 

Let's say you have a file input called input_file defined in the json. DNAnexus automatically gives you $input_file_prefix, which is the filename stripped of the required extension as defined by the json, and $input_file_name which is the filename of input_file.

For example if you have a vcf_file input which accepts .vcf or .vcf.gz files and you use myfile.vcf as input, then $vcf_file_name = myfile.vcf and $vcf_file_prefix = myfile

**Review by woook — APPROVED** [review]
:lgtm: on the files I've reviewed

> Reviewed 1 of 6 files at r1, 3 of 4 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf_qc/2#-:-M4wtayi4FcXIkMjHs_t:b-3cjnz4)* status: all files reviewed, 1 unresolved discussion (waiting on @Yu-jinKim)

**Review by Yu-jinKim — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf_qc/2)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by Yu-jinKim — APPROVED** [review]
> Reviewed 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf_qc/2)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by woook** [comment]
Where is the tarball? Don't you need to add it to the applet (& into github)?
Also, I don't think you should be accepting PRs and merging for your own changes...

**Pull request merged**
