### PR TITLE
DI-809 refactor

### LINKED ISSUE #4: Remove eggd_ prefix from app name.
App should be named vcf_qc in DNAnexus, but the repo should remain as eggd_vcf_qc

### LINKED ISSUE #5: Update to meet current standards
- Update ubuntu version
- remove version from filename
- remove exec depends and package pysam in the app
- remove suggestion of outdated file
- make into app (add developer and authorised user fields)
- Update bedtools version (provide as asset?)
- Code could do with some more comments
- Update readme (inferred gender isn't used)

### LINKED ISSUE #6: ref_count incorrectly assigned and other assumptions
https://github.com/eastgenomics/eggd_vcf_qc/blob/97a20c1c200d3cdd66b7bd7dbbf43e1a8b948a4c/resources/usr/bin/vcf_QC.py#L70C57-L70C63

If we print the values of this line: 
```
            ref_count, alt_count = counts[ gts[0]], counts[ gts[1]]
            print(gts[0],gts[1],ref_count,alt_count,counts)
```

1 1 5 5 (0, 5) <--- ref_count incorrectly assigned as 5 where it should be 0
1 1 2 2 (0, 2)
0 1 6 8 (6, 8) <--- het variants with one alt are ok
1 2 6 5 (0, 6, 5) <--- This also assumes ref_count is 5 instead of 0, and doesn't account for the ALT with most reads

### LINKED ISSUE #7: Wrong label outputted for X het-hom ratio
https://github.com/eastgenomics/eggd_vcf_qc/blob/97a20c1c200d3cdd66b7bd7dbbf43e1a8b948a4c/resources/usr/bin/vcf_QC.py#L137

Although X het-hom ratio calculated, the label resulted is returned as X hom-het ratio

https://github.com/eastgenomics/eggd_vcf_qc/blob/97a20c1c200d3cdd66b7bd7dbbf43e1a8b948a4c/resources/usr/bin/vcf_QC.py#L121

This should also be adressed in the readme

### LINKED ISSUE #8: Add -u option to reduce number of duplicates
https://github.com/eastgenomics/eggd_vcf_qc/blob/97a20c1c200d3cdd66b7bd7dbbf43e1a8b948a4c/resources/usr/bin/vcf_QC.py#L27

When using bed files to intersect the vcf, if the bed file has duplicated or overlapping regions current intersect returns one vcf entry for each overlap resulting in duplicated variants. 

When running with GCF_000001405.39_GRCh38.p13_genomic.exon_5bp.tsv the resulting AAF histogram looks like this:
image

When running with a merged version of the above file the number of variants is significantly reduced (note the change in y axis scale):
image

This also affects the calculation of the mean het ratio value which is used for PASS/FAIL decisions for rare disease samples. With the original bed used the value outputted would fail the sample as it was skewed by duplication of 'bad' variants.

### PR DESCRIPTION
**Pull request by jethror1**
- refactor of app to Python
- remove external dependencies, switch bedtools to using asset
- add `-u` to bedtools intersect to remove duplicate variants from overlapping bed file regions
- add unit tests
  - coverage at 97%
- ensure only autosomes used for mean het, mean hom and het:hom calculations
- fix all the issues so calculations are actually correct
  - fixes #4 
  - fixes #5 
  - fixes #6 
  - fixes #7 
  - fixes #8 
- test job: https://platform.dnanexus.com/panx/projects/GqZ0Zp84bZv0G622qpqKf32y/monitor/job/GqfYjJQ4bZv102YgYZQ1xb23GqfYF5j4bZvPQ0kV2xZ1zX4y

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf_qc/9)

### CODE REVIEW

**Review by Yu-jinKim — CHANGES_REQUESTED** [review]
> Reviewed 20 of 20 files at r1.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf_qc/9)* status: 18 of 20 files reviewed, 2 unresolved discussions (waiting on @jethror1 and @mattgarner)

___
*[`src/vcf_qc.py` line 7 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcf_qc/9#-O7Dd4BU9WAAJKFGcPmv:-O7Dd4BU9WAAJKFGcPmw:bij2owx) ([raw file](https://github.com/eastgenomics/eggd_vcf_qc/blob/11993a1aa5292883fbfa722688e42a7dd9725f7f/src/vcf_qc.py#L7)):*
> ```Python
> import sys
> 
> if os.path.exists('/home/dnanexus'):
> ```

is that a pytest thing? i.e. you need to install packages in dnanexus mode but not in pytest mode because you have a step for that?
also it's disgusting having to install packages like that in dnanexus
___
*[`src/vcf_qc.py` line 73 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcf_qc/9#-O7Df0L4CzMPO7FV0ysM:-O7Df0L4CzMPO7FV0ysN:b-vnwatz) ([raw file](https://github.com/eastgenomics/eggd_vcf_qc/blob/11993a1aa5292883fbfa722688e42a7dd9725f7f/src/vcf_qc.py#L73)):*
> ```Python
>     """
>     autosomes = [
>         x for y in [(str(x), f"chr{x}") for x in range(1, 23)] for x in y
> ```

brain hurt a bit trying to understand that

**Review by jethror1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf_qc/9)* status: 18 of 20 files reviewed, 2 unresolved discussions (waiting on @mattgarner and @Yu-jinKim)

___
*[`src/vcf_qc.py` line 7 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcf_qc/9#-O7Dd4BU9WAAJKFGcPmv:-O7Dh9cKB0kMwj-raoVC:bfsz46k) ([raw file](https://github.com/eastgenomics/eggd_vcf_qc/blob/11993a1aa5292883fbfa722688e42a7dd9725f7f/src/vcf_qc.py#L7)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

is that a pytest thing? i.e. you need to install packages in dnanexus mode but not in pytest mode because you have a step for that?
also it's disgusting having to install packages like that in dnanexus
</blockquote></details>

its really just a DNAnexus thing, the other option is to have it in `execDepends` in the dxapp.json, but that means it pulls from pypi. When I asked support I got a worse answer so went with this which works fine. Also allows to keep running it locally too and not install packages
___
*[`src/vcf_qc.py` line 73 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcf_qc/9#-O7Df0L4CzMPO7FV0ysM:-O7Dhc8X76gNJGHNimmG:bhj4k1w) ([raw file](https://github.com/eastgenomics/eggd_vcf_qc/blob/11993a1aa5292883fbfa722688e42a7dd9725f7f/src/vcf_qc.py#L73)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

brain hurt a bit trying to understand that
</blockquote></details>

added a comment, its just unpacking to a single list to have both with and without the chr prefix, else it ends up a list of tuples

**Review by mattgarner — CHANGES_REQUESTED** [review]
> Reviewed 12 of 20 files at r1, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf_qc/9)* status: 18 of 20 files reviewed, 7 unresolved discussions (waiting on @jethror1 and @Yu-jinKim)

___
*[`src/vcf_qc.py` line 73 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcf_qc/9#-O7Df0L4CzMPO7FV0ysM:-O7DniqX9xgF2_MiaScq:b-3y504b) ([raw file](https://github.com/eastgenomics/eggd_vcf_qc/blob/11993a1aa5292883fbfa722688e42a7dd9725f7f/src/vcf_qc.py#L73)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

added a comment, its just unpacking to a single list to have both with and without the chr prefix, else it ends up a list of tuples
</blockquote></details>

maybe not using variable names x and y in context of autosomes (when not intending to refer to chrX/chrY) is a good idea for less brain hurt
___
*[`src/vcf_qc.py` line 74 at r5](https://reviewable.io/reviews/eastgenomics/eggd_vcf_qc/9#-O7Dohpp7NErqnib_cFw:-O7Dohpp7NErqnib_cFx:b-yqkx0e) ([raw file](https://github.com/eastgenomics/eggd_vcf_qc/blob/ae857d99e7cc27adbe6bca21427531188a1b3626/src/vcf_qc.py#L74)):*
> ```Python
>     # build single list both with and without prefix
>     autosomes = [
>         x for y in [(str(x), f"chr{x}") for x in range(1, 23)] for x in y
> ```

Looks like we call this function for each variant assessed, meaning we generate an identical list over and over and over. Is there a better way whereby this list is generated once for all checks?



_Code quote:_
```Python
x for y in [(str(x), f"chr{x}") for x in range(1, 23)] for x in y
```
___
*[`src/vcf_qc.py` line 115 at r5](https://reviewable.io/reviews/eastgenomics/eggd_vcf_qc/9#-O7DsGjd1n4_BapZ8tRg:-O7DsGjd1n4_BapZ8tRh:bnj7und) ([raw file](https://github.com/eastgenomics/eggd_vcf_qc/blob/ae857d99e7cc27adbe6bca21427531188a1b3626/src/vcf_qc.py#L115)):*
> ```Python
>     }
> 
>     variants = autosomes = x_variants = 0
> ```

Since these are also counts, would it make sense for them to be in the counts dict?



_Code quote:_
```Python
variants = autosomes = x_variants = 0
```
___
*[`src/vcf_qc.py` line 121 at r5](https://reviewable.io/reviews/eastgenomics/eggd_vcf_qc/9#-O7DqRaZ9yjFZIilD3Gq:-O7DqRaZ9yjFZIilD3Gr:b2m29hw) ([raw file](https://github.com/eastgenomics/eggd_vcf_qc/blob/ae857d99e7cc27adbe6bca21427531188a1b3626/src/vcf_qc.py#L121)):*
> ```Python
> 
>         if not all(x in sample_fields for x in ['AD', 'DP', 'GT']):
>             # TODO - do we still want to do this? does this even happen?
> ```

a vcf without these is possible. I guess the point was to check the fields we need are present and fail slightly earlier if not

Let's keep it, probably _slightly_ easier for someone to interpret this than the error message that would come from a missing field later

Maybe the message itself could be a little more specific about which fields may be missing



_Code quote:_
```Python
            # TODO - do we still want to do this? does this even happen?
```
___
*[`src/vcf_qc.py` line 146 at r5](https://reviewable.io/reviews/eastgenomics/eggd_vcf_qc/9#-O7DuDKr6EP645HnDYpp:-O7DuDKr6EP645HnDYpq:bqjcy0u) ([raw file](https://github.com/eastgenomics/eggd_vcf_qc/blob/ae857d99e7cc27adbe6bca21427531188a1b3626/src/vcf_qc.py#L146)):*
> ```Python
>                 x_variants += 1
>                 counts['x_hom'].append(non_ref_aaf)
>         else:
> ```

Could we handle GT=0/1 (ref/alt1) vs GT=1/2 (alt1/alt2) differently? 

This het ratio produced by this tool can give an indication of capture efficiency differences between ref vs alt alleles, but if we include GT=1/2 in the mix then we're sometimes comparing alt vs alt and so diluting that signal a bit



_Code quote:_
```Python
e
```
___
*[`src/vcf_qc.py` line 196 at r5](https://reviewable.io/reviews/eastgenomics/eggd_vcf_qc/9#-O7DssiV1SKMz-TQ6BwW:-O7DssiV1SKMz-TQ6BwX:b1ip3zt) ([raw file](https://github.com/eastgenomics/eggd_vcf_qc/blob/ae857d99e7cc27adbe6bca21427531188a1b3626/src/vcf_qc.py#L196)):*
> ```Python
>         # we don't have both het and hom variants => TODO figure out what to do
>         # assume this is an empty vcf, and we'd just want to output something still?
>         return ratios
> ```

If this happens something is drastically wrong and other qc detects it, so not too concerned about this. Setting to None makes sense



_Code quote:_
```Python
        # we don't have both het and hom variants => TODO figure out what to do
        # assume this is an empty vcf, and we'd just want to output something still?
        return ratios
```

**Review by mattgarner — COMMENTED** [review]
> Reviewed 5 of 20 files at r1.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf_qc/9)* status: 18 of 20 files reviewed, 7 unresolved discussions (waiting on @jethror1 and @Yu-jinKim)

**Review by jethror1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf_qc/9)* status: 18 of 20 files reviewed, 7 unresolved discussions (waiting on @mattgarner and @Yu-jinKim)

___
*[`src/vcf_qc.py` line 73 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vcf_qc/9#-O7Df0L4CzMPO7FV0ysM:-O7Dw0A3EjmTg2BQQKxU:b-402ocq) ([raw file](https://github.com/eastgenomics/eggd_vcf_qc/blob/11993a1aa5292883fbfa722688e42a7dd9725f7f/src/vcf_qc.py#L73)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

maybe not using variable names x and y in context of autosomes (when not intending to refer to chrX/chrY) is a good idea for less brain hurt
</blockquote></details>

ha yes, didn't think about that, have switched to i, j
___
*[`src/vcf_qc.py` line 74 at r5](https://reviewable.io/reviews/eastgenomics/eggd_vcf_qc/9#-O7Dohpp7NErqnib_cFw:-O7DwUgO2X6-mzMEjJeW:b-3s87ds) ([raw file](https://github.com/eastgenomics/eggd_vcf_qc/blob/ae857d99e7cc27adbe6bca21427531188a1b3626/src/vcf_qc.py#L74)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Looks like we call this function for each variant assessed, meaning we generate an identical list over and over and over. Is there a better way whereby this list is generated once for all checks?
</blockquote></details>

we could remove the list generating into the calling function so it's only once, then pass it in but that makes testing worse. Alternatively add a `generate_autosomes()` function to call, then have this take in the output from that which would be fine I guess.

Since this is a defined list of 24 being generated, then iterating over to split the tuples I'm not overly concerned with performance vs readability of keeping the context in single function, but I appreciate the thought of not wanting needless inefficiency (especially if this was doing something more intense / API querying etc) :slightly_smiling_face: 

demonstrating the time for that list comp:
```
$ python3 -m timeit -u sec '[i for j in [(str(i), f"chr{i}") for i in range(1, 23)] for i in j]'
50000 loops, best of 5: 6.3e-06 sec per loop
```
___
*[`src/vcf_qc.py` line 115 at r5](https://reviewable.io/reviews/eastgenomics/eggd_vcf_qc/9#-O7DsGjd1n4_BapZ8tRg:-O7Dz-H6Bv4IkrFwa7kU:boesdg3) ([raw file](https://github.com/eastgenomics/eggd_vcf_qc/blob/ae857d99e7cc27adbe6bca21427531188a1b3626/src/vcf_qc.py#L115)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Since these are also counts, would it make sense for them to be in the counts dict?
</blockquote></details>

I could, I just wanted them there for a simple count at the end of the function, I don't use them anywhere else
___
*[`src/vcf_qc.py` line 121 at r5](https://reviewable.io/reviews/eastgenomics/eggd_vcf_qc/9#-O7DqRaZ9yjFZIilD3Gq:-O7Dz6Wx6wlPwIz8KWEc:b-8gsiak) ([raw file](https://github.com/eastgenomics/eggd_vcf_qc/blob/ae857d99e7cc27adbe6bca21427531188a1b3626/src/vcf_qc.py#L121)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

a vcf without these is possible. I guess the point was to check the fields we need are present and fail slightly earlier if not

Let's keep it, probably _slightly_ easier for someone to interpret this than the error message that would come from a missing field later

Maybe the message itself could be a little more specific about which fields may be missing
</blockquote></details>

so print a warning and continue? Shall add that since it makes sense
___
*[`src/vcf_qc.py` line 146 at r5](https://reviewable.io/reviews/eastgenomics/eggd_vcf_qc/9#-O7DuDKr6EP645HnDYpp:-O7E02cu0YJumxhVxgq9:bi6i50p) ([raw file](https://github.com/eastgenomics/eggd_vcf_qc/blob/ae857d99e7cc27adbe6bca21427531188a1b3626/src/vcf_qc.py#L146)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Could we handle GT=0/1 (ref/alt1) vs GT=1/2 (alt1/alt2) differently? 

This het ratio produced by this tool can give an indication of capture efficiency differences between ref vs alt alleles, but if we include GT=1/2 in the mix then we're sometimes comparing alt vs alt and so diluting that signal a bit
</blockquote></details>

sure, what would you like doing? do you want them just excluding from the mean_het and het:hom ratio and adding to their own field?
___
*[`src/vcf_qc.py` line 196 at r5](https://reviewable.io/reviews/eastgenomics/eggd_vcf_qc/9#-O7DssiV1SKMz-TQ6BwW:-O7E0SL-6uKmoa7tEfsU:b-o7ltdk) ([raw file](https://github.com/eastgenomics/eggd_vcf_qc/blob/ae857d99e7cc27adbe6bca21427531188a1b3626/src/vcf_qc.py#L196)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

If this happens something is drastically wrong and other qc detects it, so not too concerned about this. Setting to None makes sense
</blockquote></details>

I was more thinking if an empty vcf goes in (i.e. a sample has virtually no reads), that it still outputs _something_ so the job doesn't fail and cause downstream jobs to fail. I would hope we would pick this up in multiQC :slightly_smiling_face: 

will ditch the TODO and make sure an empty vcf works, probably should write some tests for main for this

**Review by mattgarner — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf_qc/9)* status: 19 of 20 files reviewed, 6 unresolved discussions (waiting on @jethror1 and @Yu-jinKim)

___
*[`src/vcf_qc.py` line 115 at r5](https://reviewable.io/reviews/eastgenomics/eggd_vcf_qc/9#-O7DsGjd1n4_BapZ8tRg:-O7E38aBDGIG9enACG_T:b72eo0c) ([raw file](https://github.com/eastgenomics/eggd_vcf_qc/blob/ae857d99e7cc27adbe6bca21427531188a1b3626/src/vcf_qc.py#L115)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

I could, I just wanted them there for a simple count at the end of the function, I don't use them anywhere else
</blockquote></details>

Then instead could the existing vars be renamed variants_count, autosomes_count etc, since they are counts of variants rather than variants
___
*[`src/vcf_qc.py` line 146 at r5](https://reviewable.io/reviews/eastgenomics/eggd_vcf_qc/9#-O7DuDKr6EP645HnDYpp:-O7E3wkrAVa34KrIagsr:bddxaoz) ([raw file](https://github.com/eastgenomics/eggd_vcf_qc/blob/ae857d99e7cc27adbe6bca21427531188a1b3626/src/vcf_qc.py#L146)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

sure, what would you like doing? do you want them just excluding from the mean_het and het:hom ratio and adding to their own field?
</blockquote></details>

Yeah, exclude from the I cannot really think of a way they are useful as their own separate group, but doing so does somewhat imply that they are excluded from the other group and aid understanding so let's go with that
___
*[`src/vcf_qc.py` line 196 at r5](https://reviewable.io/reviews/eastgenomics/eggd_vcf_qc/9#-O7DssiV1SKMz-TQ6BwW:-O7EBk2m7y25aF4gUQvF:b6jhk1x) ([raw file](https://github.com/eastgenomics/eggd_vcf_qc/blob/ae857d99e7cc27adbe6bca21427531188a1b3626/src/vcf_qc.py#L196)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

I was more thinking if an empty vcf goes in (i.e. a sample has virtually no reads), that it still outputs _something_ so the job doesn't fail and cause downstream jobs to fail. I would hope we would pick this up in multiQC :slightly_smiling_face: 

will ditch the TODO and make sure an empty vcf works, probably should write some tests for main for this
</blockquote></details>

I think we're agreed (though maybe I've not said what I meant in the clearest way)

**Review by jethror1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf_qc/9)* status: 17 of 21 files reviewed, 6 unresolved discussions (waiting on @mattgarner and @Yu-jinKim)

___
*[`src/vcf_qc.py` line 115 at r5](https://reviewable.io/reviews/eastgenomics/eggd_vcf_qc/9#-O7DsGjd1n4_BapZ8tRg:-O7ERwhCAgSUkJzzdN9y:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_vcf_qc/blob/ae857d99e7cc27adbe6bca21427531188a1b3626/src/vcf_qc.py#L115)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Then instead could the existing vars be renamed variants_count, autosomes_count etc, since they are counts of variants rather than variants
</blockquote></details>

Done.
___
*[`src/vcf_qc.py` line 146 at r5](https://reviewable.io/reviews/eastgenomics/eggd_vcf_qc/9#-O7DuDKr6EP645HnDYpp:-O7EYh8111_sLWP-keyW:b-9onw3f) ([raw file](https://github.com/eastgenomics/eggd_vcf_qc/blob/ae857d99e7cc27adbe6bca21427531188a1b3626/src/vcf_qc.py#L146)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Yeah, exclude from the I cannot really think of a way they are useful as their own separate group, but doing so does somewhat imply that they are excluded from the other group and aid understanding so let's go with that
</blockquote></details>

now removed and added into the counts dict to be displayed, but not included in calculations
___
*[`src/vcf_qc.py` line 196 at r5](https://reviewable.io/reviews/eastgenomics/eggd_vcf_qc/9#-O7DssiV1SKMz-TQ6BwW:-O7ERK96CbY6-HVTx7Df:b-e3pg2j) ([raw file](https://github.com/eastgenomics/eggd_vcf_qc/blob/ae857d99e7cc27adbe6bca21427531188a1b3626/src/vcf_qc.py#L196)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

I think we're agreed (though maybe I've not said what I meant in the clearest way)
</blockquote></details>

added tests for main, including one to test an empty vcf passes through with no errors

**Review by mattgarner — COMMENTED** [review]
> Reviewed 3 of 4 files at r9, 2 of 3 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf_qc/9)* status: 21 of 22 files reviewed, 2 unresolved discussions (waiting on @Yu-jinKim)

**Review by mattgarner — APPROVED** [review]
> Reviewed 1 of 3 files at r10.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf_qc/9)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jethror1)

**Review by Yu-jinKim — APPROVED** [review]
> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf_qc/9)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jethror1)

**Pull request merged**
